stages:
  - build
  - e2e

build:
  stage: build
  image: node:latest
  services:
    - docker:dind

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    TEST_DOCKER_HOST: docker

  before_script:
    - yarn install

  script:
    - DEBUG=*,-modem yarn test

  cache:
    paths:
      - node_modules

.e2e:
  image: docker/compose:1.25.0-rc4
  services:
    - docker:dind

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    TEST_DOCKER_HOST: docker

  script:
    - docker-compose -f docker-compose.e2e.yml -f $E2E_BROWSER_FILE up --exit-code-from=nodeworlds-e2e-tests

  artifacts:
    paths:
      - output/docker/*
    when: always
    expire_in: 30 days

e2e-chrome:
  stage: e2e
  extends: .e2e
  variables:
    E2E_BROWSER_FILE: docker-compose.e2e-chrome.yml

e2e-chrome-mobile:
  stage: e2e
  extends: .e2e
  variables:
    E2E_BROWSER_FILE: docker-compose.e2e-chrome-mobile.yml

e2e-firefox:
  stage: e2e
  extends: .e2e
  variables:
    E2E_BROWSER_FILE: docker-compose.e2e-firefox.yml
